forms.py
from django import forms
from django.core.mail import send_mail
from django.shortcuts import render
from django.contrib.auth.models import User

from pymongo import MongoClient

from django import forms

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField()
    profile_pic = forms.ImageField(required=True)
    bio = forms.CharField(widget=forms.Textarea, required=False)

class ProfilePictureUpdateForm(forms.Form):
    profile_pic = forms.ImageField(required=False)

    
class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)   

class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(label='Email')
    username = forms.CharField(max_length=100)

class ResetPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)  

from django import forms
from .models import Review, RATE_CHOICES

class RateForm(forms.ModelForm):
    rate = forms.ChoiceField(choices=RATE_CHOICES, widget=forms.Select(), required=True)

    class Meta:
        model = Review
        fields = ['rate']

class ReviewForm(forms.ModelForm):

    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'materialize-textarea'}), required=False)
    class Meta:
        model = Review
        fields = ['text']
        
   
        


   

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Parallax Template - Materialize</title>
  <style>


/* Add this CSS in your stylesheets or in a <style> tag within the HTML file */

/* Main Footer */
/* Add this CSS in your stylesheets or in a <style> tag within the HTML file */

/* Main Footer */
footer.page-footer.teal {
  background-color: #1a1a1a; /* Dark Gray */
  padding-top: 30px;
  padding-bottom: 30px;
  background-image: url('https://film-grab.com/wp-content/uploads/2023/03/Empire-of-Light-17.jpg');
  background-size: cover;
}

/* White Text for Headings */
footer.page-footer.teal h5.white-text {
  color: #f8f8f8; /* Light Gray */
  font-size: 24px;
  margin-bottom: 20px;
}

/* White Text for Paragraphs */
footer.page-footer.teal p.white-text {
  color: #f8f8f8; /* Light Gray */
  font-size: 16px;
  line-height: 1.6;
  margin-bottom: 30px;
}

/* Grey Text for Links */
footer.page-footer.teal a.white-text {
  color: #b3b3b3; /* Gray */
  font-size: 16px;
}

/* Brown Text for Powered By Link */
footer.page-footer.teal a.brown-text.text-lighten-3 {
  color: #c0a080; /* Light Brown */
  font-size: 14px;
}

/* Add Padding to Links */
footer.page-footer.teal ul {
  margin: 0;
  padding: 0;
}

/* Center Align Links */
footer.page-footer.teal ul {
  display: flex;
  justify-content: center;
}

/* Space Out Link Items */
footer.page-footer.teal li {
  margin: 0 15px;
}

/* Add a Separator Line */
footer.page-footer.teal .divider {
  border-top: 1px solid #333; /* Dark Gray */
  margin-top: 20px;
  margin-bottom: 20px;
}


.profile-picture-container {
        width: 50px;
        height:50px;
        border-radius: 80%;
        overflow: hidden;
        margin: 5px;
        background-color: #f2f2f2;
        display: flex;
        justify-content: center;
        text-align: center;
        top: 50px;
    }

.profile-picture {
  max-width:  60px; /* Adjust the width as needed */
  max-height: 70px; /* Adjust the height as needed */
  vertical-align: top; /* Align the image vertically */

      
        object-fit: contain;
}


  </style>
<script>

$(document).ready(function() {
    $('.dropdown-trigger').dropdown();

    // AJAX function to fetch movies by genre
    function fetchMoviesByGenre(genre) {
      $.ajax({
        url: `/movies_by_genre/${genre}/`,
        type: 'GET',
        success: function(response) {
          $('#movies-container').html(response);
        },
        error: function(xhr) {
          console.error('Error occurred while fetching movies by genre');
        },
      });
    }

    // Event handler for genre item click
    $('.genre-item').on('click', function(event) {
      event.preventDefault();
      const genre = $(this).find('a').data('genre');
      fetchMoviesByGenre(genre);
    });
  });
</script>

</script>
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>

  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container left" href="#" class="brand-logo ">CinephileXO</a>
      <ul class="right hide-on-med-and-down">
        
      
      
        
        <li><a href="{% url 'movies' %}">Movies</a></li>
        <li><a href="{% url 'favlist' %}">favorites &nbsp;&nbsp;</a></li>

        <li><a href="{% url 'top_10_movies' %}">top10</a></li>

          <li>
            <a class="dropdown-trigger" href="#" data-target="dropdown">
              Genre<i class="material-icons right"></i>
              </a>

              <ul id="dropdown" class="dropdown-content dropdown-content-bottom">
                <li class="genre-item" data-genre="Action">
                  <a href="{% url 'genre_categorize' genre='Action' %}">Action</a>
                  </li>

                <li class="genre-item" data-genre="Adventure">
                  <a href="{% url 'genre_categorize' genre='Adventure' %}">Adventure</a>
                </li>
                <li class="genre-item" data-genre="Comedy">
                <a href="{% url 'genre_categorize' genre='Biography' %}">Biography</a>
              </li>
          </ul>
        </li>
        
        <li><a href="{% url 'watchlist' %}">Watchlist &nbsp;&nbsp;</a></li>
      
        <li>
        
          <a class="dropdown-trigger" href="#" data-target="dropdown1">
            <div class="profile-picture-container">
            <img src="{{ logged_in_user_profile_pic_url }}" alt="Profile Picture" class="profile-picture">
           <i class="material-icons right"></i>
        </a></li></div>
          <ul id="dropdown1" class="dropdown-content dropdown-content-bottom">
              <li><a href="{% url 'profile' %}">Profile</a></li>
              <li><a href="{% url 'login' %}">Logout</a></li>
          </ul>
      </li>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.dropdown-trigger');
            var options = {
                // Add any necessary options for the dropdown
            };
            var instances = M.Dropdown.init(elems, options);
        });
    </script>   
     
    </div>
  </nav>


<!-- Dropdown Structure -->
 
    

      
        

{% block banner %}
{% endblock %}

  <div class="container">
    <div class="section">

    {% block content %}
    {% endblock %}

    </div>
  </div>


  <footer class="page-footer teal">
    <div class="container">
      <!--<div class="row">-->c
        <div class="col l6 s12">
          <h2>About</h2>
          <h5 class="white-text">CinephileXO</h5>
          <p class="grey-text text-lighten-4">CinephileXO is your go-to cinematic companion, offering a comprehensive movie review and rating system designed exclusively for movie enthusiasts like you. With CinephileXO, you can indulge your passion for film by accessing insightful and unbiased reviews, in-depth analysis, and carefully curated recommendations.</p>
        </div>
        <!-- 
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    -->
    <div class="divider"></div>
    <div class="container">
      <div class="row">
        <div class="col s12">
          <p class="white-text center-align">
            Powered by <a class="brown-text text-lighten-3" href="http://materializecss.com">Oreos</a>
          </p>
        </div>
      </div>
    </div>
  </footer>
  


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>

  </body>
</html>

templates/favlist.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>My favlist</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
        <!-- Add Materialize CSS and JavaScript links -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <style>


        /* Add this CSS in your stylesheets or in a <style> tag within the HTML file */
        
        /* Main Footer */
        /* Add this CSS in your stylesheets or in a <style> tag within the HTML file */
        
        /* Main Footer */
        footer.page-footer.teal {
          background-color: #1a1a1a; /* Dark Gray */
          padding-top: 30px;
          padding-bottom: 30px;
          background-image: url('https://film-grab.com/wp-content/uploads/2023/03/Empire-of-Light-17.jpg');
          background-size: cover;
        }
        
        /* White Text for Headings */
        footer.page-footer.teal h5.white-text {
          color: #f8f8f8; /* Light Gray */
          font-size: 24px;
          margin-bottom: 20px;
        }
        
        /* White Text for Paragraphs */
        footer.page-footer.teal p.white-text {
          color: #f8f8f8; /* Light Gray */
          font-size: 16px;
          line-height: 1.6;
          margin-bottom: 30px;
        }
        
        /* Grey Text for Links */
        footer.page-footer.teal a.white-text {
          color: #b3b3b3; /* Gray */
          font-size: 16px;
        }
        
        /* Brown Text for Powered By Link */
        footer.page-footer.teal a.brown-text.text-lighten-3 {
          color: #c0a080; /* Light Brown */
          font-size: 14px;
        }
        
        /* Add Padding to Links */
        footer.page-footer.teal ul {
          margin: 0;
          padding: 0;
        }
        
        /* Center Align Links */
        footer.page-footer.teal ul {
          display: flex;
          justify-content: center;
        }
        
        /* Space Out Link Items */
        footer.page-footer.teal li {
          margin: 0 15px;
        }
        
        /* Add a Separator Line */
        footer.page-footer.teal .divider {
          border-top: 1px solid #333; /* Dark Gray */
          margin-top: 20px;
          margin-bottom: 20px;
        }
        
        
        .profile-picture-container {
                width: 50px;
                height:50px;
                border-radius: 80%;
                overflow: hidden;
                margin: 5px;
                background-color: #f2f2f2;
                display: flex;
                justify-content: center;
                text-align: center;
                top: 50px;
            }
        
        .profile-picture {
          max-width:  60px; /* Adjust the width as needed */
          max-height: 70px; /* Adjust the height as needed */
          vertical-align: top; /* Align the image vertically */
        
              
                object-fit: contain;
        }
        
        
          </style>
        <script>
        
        $(document).ready(function() {
            $('.dropdown-trigger').dropdown();
        
            // AJAX function to fetch movies by genre
            function fetchMoviesByGenre(genre) {
              $.ajax({
                url: `/movies_by_genre/${genre}/`,
                type: 'GET',
                success: function(response) {
                  $('#movies-container').html(response);
                },
                error: function(xhr) {
                  console.error('Error occurred while fetching movies by genre');
                },
              });
            }
        
            // Event handler for genre item click
            $('.genre-item').on('click', function(event) {
              event.preventDefault();
              const genre = $(this).find('a').data('genre');
              fetchMoviesByGenre(genre);
            });
          });
        </script>
        
        </script>
          <!-- CSS  -->
          <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
          <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
          <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
        </head>
        <body>
        
          <nav class="white" role="navigation">
            <div class="nav-wrapper container">
              <a id="logo-container left" href="#" class="brand-logo ">CinephileXO</a>
              <ul class="right hide-on-med-and-down">
                
              
              
                
                <li><a href="{% url 'movies' %}">Movies</a></li>
                <li><a href="{% url 'favlist' %}">favorites &nbsp;&nbsp;</a></li>
        
                <li><a href="{% url 'top_10_movies' %}">top10</a></li>
        
                  <li>
                    <a class="dropdown-trigger" href="#" data-target="dropdown">
                      Genre<i class="material-icons right"></i>
                      </a>
        
                      <ul id="dropdown" class="dropdown-content dropdown-content-bottom">
                        <li class="genre-item" data-genre="Action">
                          <a href="{% url 'genre_categorize' genre='Action' %}">Action</a>
                          </li>
        
                        <li class="genre-item" data-genre="Adventure">
                          <a href="{% url 'genre_categorize' genre='Adventure' %}">Adventure</a>
                        </li>
                        <li class="genre-item" data-genre="Comedy">
                        <a href="{% url 'genre_categorize' genre='Biography' %}">Biography</a>
                      </li>
                  </ul>
                </li>
                
                <li><a href="{% url 'watchlist' %}">Watchlist &nbsp;&nbsp;</a></li>
              
                <li>
                
                  <a class="dropdown-trigger" href="#" data-target="dropdown1">
                    <div class="profile-picture-container">
                    <img src="{{ logged_in_user_profile_pic_url }}" alt="Profile Picture" class="profile-picture">
                   <i class="material-icons right"></i>
                </a></li></div>
                  <ul id="dropdown1" class="dropdown-content dropdown-content-bottom">
                      <li><a href="{% url 'profile' %}">Profile</a></li>
                      <li><a href="{% url 'login' %}">Logout</a></li>
                  </ul>
              </li>
              <script>
                document.addEventListener('DOMContentLoaded', function() {
                    var elems = document.querySelectorAll('.dropdown-trigger');
                    var options = {
                        // Add any necessary options for the dropdown
                    };
                    var instances = M.Dropdown.init(elems, options);
                });
            </script>   
             
            </div>
          </nav>
</head>
<body>
    <h2><center>My favlist</h2></center>
    <div class="movies-container">
        <ul class="movies-list">
            {% for movie in movies %}
                <div class="movie-card">
                    <div class="movie-thumbnail">
                        <img src="/media/{{ movie.thumbnail }}" alt="{{ movie.title }}">
                    </div>
                    <div class="movie-details">
                        <h2><a href="{% url 'movie_details' imdb_id=movie.imdbID %}">{{ movie.title }}</a></h2>

                        <p><strong>Year:</strong> {{ movie.year }}</p>
                        <p><strong>Director:</strong> {{ movie.director }}</p>
                        <p><strong>Genre:</strong> {{ movie.genre }}</p>
                        {% if movie.avg_rating %}
                        <p><strong>Cine Rating: </strong>{{ movie.avg_rating }}</p>
                    {% else %}
                        <p><strong>Cine Rating:</strong>0</hp>
                    {% endif %}
                          <!--<p>Description: {{ movie.description }}</p>-->
                        </div>
                    </div>
                
            {% endfor %}
        </ul>
    </div>
</body>
</html>

<style>
.movies-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
}

.movies-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
}

.movie-card {
    width: 30.7%;
    margin: 20px;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.movie-thumbnail img {
    width: 100%;
    height: auto;
}

.movie-details h2 {
    font-size: 18px;
    font-weight: bold;
    margin-top: 10px;
}

.movie-details p {
    font-size: 14px;
    margin: 5px 0;
}
</style>

templates/genre_categorize.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<style>
.movies-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
}

.movies-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
}

.movie-card {
    width: 14.7%;
    margin: 20px;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.movie-thumbnail img {
    width: 100%;
    height: auto;
}

.movie-details h2 {
    font-size: 18px;
    font-weight: bold;
    margin-top: 10px;
}

.movie-details p {
    font-size: 14px;
    margin: 5px 0;
}
</style>
</head>
<body>
        <!-- Add Materialize CSS and JavaScript links -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <style>


        /* Add this CSS in your stylesheets or in a <style> tag within the HTML file */
        
        /* Main Footer */
        /* Add this CSS in your stylesheets or in a <style> tag within the HTML file */
        
        /* Main Footer */
        footer.page-footer.teal {
          background-color: #1a1a1a; /* Dark Gray */
          padding-top: 30px;
          padding-bottom: 30px;
          background-image: url('https://film-grab.com/wp-content/uploads/2023/03/Empire-of-Light-17.jpg');
          background-size: cover;
        }
        
        /* White Text for Headings */
        footer.page-footer.teal h5.white-text {
          color: #f8f8f8; /* Light Gray */
          font-size: 24px;
          margin-bottom: 20px;
        }
        
        /* White Text for Paragraphs */
        footer.page-footer.teal p.white-text {
          color: #f8f8f8; /* Light Gray */
          font-size: 16px;
          line-height: 1.6;
          margin-bottom: 30px;
        }
        
        /* Grey Text for Links */
        footer.page-footer.teal a.white-text {
          color: #b3b3b3; /* Gray */
          font-size: 16px;
        }
        
        /* Brown Text for Powered By Link */
        footer.page-footer.teal a.brown-text.text-lighten-3 {
          color: #c0a080; /* Light Brown */
          font-size: 14px;
        }
        
        /* Add Padding to Links */
        footer.page-footer.teal ul {
          margin: 0;
          padding: 0;
        }
        
        /* Center Align Links */
        footer.page-footer.teal ul {
          display: flex;
          justify-content: center;
        }
        
        /* Space Out Link Items */
        footer.page-footer.teal li {
          margin: 0 15px;
        }
        
        /* Add a Separator Line */
        footer.page-footer.teal .divider {
          border-top: 1px solid #333; /* Dark Gray */
          margin-top: 20px;
          margin-bottom: 20px;
        }
        
        
        .profile-picture-container {
                width: 50px;
                height:50px;
                border-radius: 80%;
                overflow: hidden;
                margin: 5px;
                background-color: #f2f2f2;
                display: flex;
                justify-content: center;
                text-align: center;
                top: 50px;
            }
        
        .profile-picture {
          max-width:  60px; /* Adjust the width as needed */
          max-height: 70px; /* Adjust the height as needed */
          vertical-align: top; /* Align the image vertically */
        
              
                object-fit: contain;
        }
        
        
          </style>
        <script>
        
        $(document).ready(function() {
            $('.dropdown-trigger').dropdown();
        
            // AJAX function to fetch movies by genre
            function fetchMoviesByGenre(genre) {
              $.ajax({
                url: `/movies_by_genre/${genre}/`,
                type: 'GET',
                success: function(response) {
                  $('#movies-container').html(response);
                },
                error: function(xhr) {
                  console.error('Error occurred while fetching movies by genre');
                },
              });
            }
        
            // Event handler for genre item click
            $('.genre-item').on('click', function(event) {
              event.preventDefault();
              const genre = $(this).find('a').data('genre');
              fetchMoviesByGenre(genre);
            });
          });
        </script>
        
        </script>
          <!-- CSS  -->
          <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
          <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
          <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
        </head>
        <body>
        
          <nav class="white" role="navigation">
            <div class="nav-wrapper container">
              <a id="logo-container left" href="#" class="brand-logo ">CinephileXO</a>
              <ul class="right hide-on-med-and-down">
                
              
              
                
                <li><a href="{% url 'movies' %}">Movies</a></li>
                <li><a href="{% url 'favlist' %}">favorites &nbsp;&nbsp;</a></li>
        
                <li><a href="#">Articles</a></li>
        
                  <li>
                    <a class="dropdown-trigger" href="#" data-target="dropdown">
                      Genre<i class="material-icons right"></i>
                      </a>
        
                      <ul id="dropdown" class="dropdown-content dropdown-content-bottom">
                        <li class="genre-item" data-genre="Action">
                          <a href="{% url 'genre_categorize' genre='Action' %}">Action</a>
                          </li>
        
                        <li class="genre-item" data-genre="Adventure">
                          <a href="{% url 'genre_categorize' genre='Adventure' %}">Adventure</a>
                        </li>
                        <li class="genre-item" data-genre="Comedy">
                        <a href="{% url 'genre_categorize' genre='Biography' %}">Biography</a>
                      </li>
                  </ul>
                </li>
                
                <li><a href="{% url 'watchlist' %}">Watchlist &nbsp;&nbsp;</a></li>
              
                <li>
                
                  <a class="dropdown-trigger" href="#" data-target="dropdown1">
                    <div class="profile-picture-container">
                    <img src="{{ logged_in_user_profile_pic_url }}" alt="Profile Picture" class="profile-picture">
                   <i class="material-icons right"></i>
                </a></li></div>
                  <ul id="dropdown1" class="dropdown-content dropdown-content-bottom">
                      <li><a href="{% url 'profile' %}">Profile</a></li>
                      <li><a href="{% url 'login' %}">Logout</a></li>
                  </ul>
              </li>
              <script>
                document.addEventListener('DOMContentLoaded', function() {
                    var elems = document.querySelectorAll('.dropdown-trigger');
                    var options = {
                        // Add any necessary options for the dropdown
                    };
                    var instances = M.Dropdown.init(elems, options);
                });
            </script>   
             
            </div>
          </nav>

<h2><center>Movies in {{ genre }} Genre</h2></body></center>    <ul class="movies-list">
        {% for movie in movies %}
        <li class="movie-card">
            <div class="movie-thumbnail">
                <img src="/media/{{ movie.thumbnail }}" alt="{{ movie.title }}">
            </div>
            <div class="movie-details">
                <h2><a href="{% url 'movie_details' imdb_id=movie.imdbID %}">{{ movie.title }}</a></h2>
                <p><strong>Year:</strong> {{ movie.year }}</p>
                <p><strong>Director:</strong> {{ movie.director }}</p>
                <p><strong>Genre:</strong> {{ movie.genre }}</p>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

</body>
</html>

templates/genreco.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recommended Movies</title>
</head>
<body>
    <h1>Recommended Movies</h1>

    <h2>Top Recommended Movies:</h2>
    <ul>
        {% for movie, rating in recommended_movies %}
            <li>{{ movie.title }} (Rating: {{ rating }}) </li>
        {% endfor %}
    </ul>

    <!-- You can add more HTML here as needed -->

</body>
</html>

templates/rate.html
{% extends 'base.html' %}

{% block content %}
  <h1>Rate Movie</h1>

  <form method="POST" action="{% url 'rate_movie' imdb_id=movie.imdbID %}">
    {% csrf_token %}
    
    <!-- Display movie information -->
    <h2>{{ movie.title }}</h2>
    <p>{{ movie.description }}</p>
    
    <!-- Display rate form fields -->
    {{ form.as_p }}
    
    <!-- Submit button -->
    <button type="submit">Rate</button>
  </form>
{% endblock %}

templates/rate_movie_popup.html
<!-- rate_movie_popup.html -->
<div id="rate-movie-popup">
    <h2>Rate the Movie</h2>
    <form id="rate-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit Rating</button>
    </form>
  </div>
  

templates/registration_success.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Registration Successful</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>Registration Successful</h1>
    <p>Thank you for registering! Your account has been created successfully.</p>
    <a href="{% url 'login' %}">Login</a>
</body>
</html>

templates/reset_password.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>Reset Password</title>
</head>
<body>
    <br><br><br>
    <div class="container">
        <div class="logo1"><img src="{% static 'img/group4.png' %}" alt="Unsplashed background img 1"></div>

    <h1>Reset Password</h1>
    {% if error_message %}
        <p class="error">{{ error_message }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <label for="id_password">New Password:</label>
        <input type="password" name="password" id="id_password">
        <br>
        <label for="id_confirm_password">Confirm Password:</label>
        <input type="password" name="confirm_password" id="id_confirm_password">
        <br>
        <button type="submit">Reset Password</button>
    </form>
</div>
</body>
</html>

<style>
    body {
        background-color: #f5f5f7;
        font-family: Helvetica, Arial, sans-serif;
        margin: 0;
        padding: 0;
    }
    
    .container {
        max-width: 400px;
        margin: 0 auto;
        padding: 40px 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        text-align: center;
    }
    
    h1 {
        font-size: 24px;
        margin-bottom: 20px;
        color: #333;
    }
    
    .error-message {
        color: #ff3b30;
        margin-bottom: 10px;
    }
    
    .form-group {
        margin-bottom: 20px;
        text-align: left;
    }
    
    label {
        display: block;
        font-size: 14px;
        font-weight: bold;
        margin-bottom: 5px;
        color: #666;
        text-align: left;
    }
    
    input[type="password"] {
        width: 95%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 14px;
    }
    
   
    
    
    button[type="submit"] {
        display: block;
        width: 95%;
        padding: 10px;
        background-color: #000;
        color: #fff;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
    }

    .logo1 {
   
   
    
   text-align: center;
}

.logo1 img {
   max-width: 15%;
   height: auto;
   margin-bottom: -35px;
  
}
    </style>